spring.application.name=Tri-Service-Profiler
spring.profiles.active=dev



# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.database=0
spring.data.redis.timeout=2000


# Rate Limiting Configuration
rate.limit.auth.requests=10
rate.limit.auth.duration.minutes=1
rate.limit.api.requests=60
rate.limit.api.duration.minutes=1

